### ISSUE TITLE
Having support for multiple CodeBuilds & CodePipeline

### ISSUE THREAD

**Issue by anshulgargamway** [awslabs/aws-codeservices-plugins-for-backstage#10]
Can you suggest what we need to do when we have multiple CodeBuild & CodePipeline linked to same code respository ?

**Comment by nimakaviani** [comment]
hi @anshulgargamway ,

for now we only support one instance of each of the CodeSuite services as part of the same backstage component. One option you have is to include each set under a new backstage component.

We dont have any immediate plans to include multiple identical CodeSuite components as part of a single backstage component unless we see the pattern repeat itself.

**Comment by niallthomson** [comment]
@anshulgargamway it would be helpful to understand more of how these multiple CodeBuild and CodePipeline instances are configured and how you would potentially see something like this fit together.

Are these instances for a single component all in the same AWS account or distributed?
How could we identify these given the annotation system of Backstage? Could we locate them by tags?

**Comment by anshulgargamway** [comment]
@niallthomson  & @nimakaviani  thanks for response.
Currently what I am observing we need to use ARN to identify code suite services. 
In our case we have multiple codesuite services linked to single component and all present in same AWS Account and we can identify them via tags but yes there can be situations in more complex cases where

**Comment by anshulgargamway** [comment]
@niallthomson Thanks for coming back.
1. We have multiple Pipelines and CodeBuilds linked to single Component (Microservice/API/Library/Website)
2. We are thinking to have have backstage as a single glass of pane where respective team can view there all pipelines/codebuilds/logs rather then going into AWS Account and identify those.
3. If possible we can have some inflated permission granted to user who can approve certain stages of pipeline directly from backstage.

**Comment by niallthomson** [comment]
@anshulgargamway because we're still learning how organizations leverage Backstage and AWS differently I think the most practical way forward here is to make the UI widgets more flexible to allow you to use your own custom annotations.

If we take CodePipeline as an example, currently you use this annotation which we automatically pick up from the current entity:

```
aws.amazon.com/aws-codepipeline: arn:aws:codepipeline:us-west-2:111111111:example-pipeline
```

However, with some minor changes we could allow you to override how the ARN is provided to the UI widgets so you do something like this on your entities:

```
myorg.com/pipeline1: arn:aws:codepipeline:us-west-2:111111111:example-pipeline1
myorg.com/pipeline2: arn:aws:codepipeline:us-west-2:111111111:example-pipeline2
```

It would then be up to you to create multiple instances of the UI widgets with the different ARNs, for example:

```jsx
<AWSCodePipelineWidget arn={getMyOrgPipeline1}/>
<AWSCodePipelineWidget arn={getMyOrgPipeline2}/>
```

**Comment by anshulgargamway** [comment]
@niallthomson  Thanks for coming back but the above might work partially.
For example if one component is having 2 pipelines and other have 3 pipelines. Then we might need to modify catalog-info.yml file of one component to have 2 ARNs and other with 3 ARNs which is tedious but ok but for maintaining the custom widget logic might be difficult right as backstage is common application for multiple component which may have varying number of pipelines.

I was thinking if we can have some resource tags specified on catalog-info.yaml and based on thouse tags it identifies all the pipelines. This way we would be able to have better control.

In addition to above suggestion if it is possible to display different stages & actions of pipelines. As of now only pipeline status is coming in widget.

**Comment by niallthomson** [comment]
That makes sense. The only other option right now I can think of you create a comma-separated list of ARNs as an annotation, which is something I hesitant to put in this plugin right now.

If we were able to pull back multiple CodePipeline resources for a single component by tag does ordering matter with regards to the UI?

**Comment by anshulgargamway** [comment]
@niallthomson : Ordering is not necessary as I think. But may be we can sort the list alphabetically.

**Comment by darrenlewisexperian** [comment]
I also have multiple CodeSuite resources for a single component, so would find this very useful. We do have CodeSuite resources spread across multiple accounts though.

**Comment by niallthomson** [comment]
@darrenlewisexperian it would be great to get more insight from you to help us design this feature. If we were able to look up multiple CodeSuite resources using some sort of AWS tag mapping would that fit your use-case? How much control would you want over, for example, the ordering of multiple CodeBuild projects on a single entity page? Would you want to see multiple entity cards on the overview or in a separate tab similar to CI/CD?

**Comment by darrenlewisexperian** [comment]
I'm just doing a POV with Backstage at the mo, so am pretty new to it. However, what I had thought of in my head is that the plugin itself wouldn't necessarily be responisble for determining how multiple CodeBuilds/CodePipelines are displayed. Initially I was just thinking of the plugin making the cards available and it's up to the consumer of the plugin to decide how/where the cards are displayed? For us, we'll be putting them all into a CI/CD tab.

In terms of finding the AWS resources, I don't think using tags would work by themselves. We tag our CodeSuite resources but they all have the same tags for the same Component as they're all part of the same stack. Tags and CodeBuild project name/CodePipeline name might work or ARN's might be easier like you describe in https://github.com/awslabs/aws-codesuite-plugins-for-backstage/issues/10#issuecomment-1385519618.

Does that help?

**Comment by vinodkumar4** [comment]
Hey, we are also having similar use case where we are using different environments (dev, staging and prod), each having at least 2 pipelines, one for Infrastructure and another for application code and in some cases more than 2 like some glue pipeline and so on. 
All these pipelines are part of Github repositories and most of repo has develop, preprod and production branches deploying to dev, staging and prod environments.

So having some sort of separation in backstage per environment and then pull all pipelines using tags or something similar could be useful instead of adding a hard-code ARN of the pipelines.
