### ISSUE TITLE
Add AWS codecommit support

### ISSUE THREAD

**Issue by gianluca-sabena** [awslabs/aws-codeservices-plugins-for-backstage#124]
Add support for [AWS code commit](https://aws.amazon.com/codecommit/) in backstage 
* support catalog for git repositories
* support template/scaffolder <https://backstage.io/docs/reference/plugin-scaffolder-backend>

**Comment by Michaell99** [comment]
Any Idea if someone going to do it?

**Comment by niallthomson** [comment]
Let me look in to the APIs available a bit more and see what would be feasible.

**Comment by bassedOutt** [comment]
@niallthomson Any updates?

**Comment by niallthomson** [comment]
Hi folks,

We have started a new project to better scale our Backstage plugin efforts. This includes a first pass at a scaffolder action for CodeCommit.

For other integration related to CodeCommit I would really appreciate if you would open a new issue in the below repository.

https://github.com/awslabs/backstage-plugins-for-aws
