### ISSUE TITLE
Code Deploy - Add Total Number of Deployments 

### ISSUE THREAD

**Issue by regicsolutions** [awslabs/aws-codeservices-plugins-for-backstage#13]
This feature request is to add the total number of deployments for Code Deploy similar to what is already in place for Code Build.

**Comment by niallthomson** [comment]
We have started a new project to better scale our efforts regarding Backstage plugins. The functionality in this repository is being migrated. If this issue is still relevant please create a new issue in this repository:

https://github.com/awslabs/backstage-plugins-for-aws
