### ISSUE TITLE
Add proper pagination

### ISSUE THREAD

**Issue by drodil** [awslabs/aws-codeservices-plugins-for-backstage#167]
When there are lots of CodePipeline executions, loading the table takes forever. For example, we have 903 executions and the load time is 58 seconds. 

Would it make sense to introduce proper pagination to the backend with query parameters and use them from the frontend so that it would not load all executions every time? Or if this is not possible from the SDK side, maybe introduce some sort of workaround or caching for this?

I think this is the same problem with CodeBuild and CodeDeploy?

**Comment by niallthomson** [comment]
Hi @drodil this will be resolved in a coming release, I'll assign this to myself and provide updates.

**Comment by drodil** [comment]
Hey @niallthomson, any updates?

**Comment by niallthomson** [comment]
I was hoping this would be resolved by now but this is still in progress

**Comment by niallthomson** [comment]
We have implemented a workaround for this in our new repository until we can look at implementing true pagination. Please see https://github.com/awslabs/backstage-plugins-for-aws
