### ISSUE TITLE
Add support for the new backend system

### ISSUE THREAD

**Issue by zcmander** [awslabs/aws-codeservices-plugins-for-backstage#184]
The new [backend system](https://backstage.io/docs/backend-system/) has been available in alpha since the v1.11.0 release in February and they hope to make it the default soo.

They do want all backend plugins available in the new system without using the compatibility layer to ease the ongoing transition. That is why they kindly request that existing backend plugins are migrated to the new [backend system](https://backstage.io/docs/backend-system/).

See reasoning:

https://github.com/backstage/backstage/issues/11611

or

https://github.com/backstage/backstage/issues/18301

**Comment by niallthomson** [comment]
this will be resolved in a coming release, I'll assign this to myself and provide updates.

**Comment by niallthomson** [comment]
We have implemented this in our new Backstage plugins code repository. Please see https://github.com/awslabs/backstage-plugins-for-aws
