### ISSUE TITLE
CodePipeline : display different stages & actions of pipelines

### ISSUE THREAD

**Issue by anshulgargamway** [awslabs/aws-codeservices-plugins-for-backstage#38]
display different stages & actions of pipelines. As of now only pipeline status is coming in widget.

**Comment by niallthomson** [comment]
We have started a new project to better scale our efforts regarding Backstage plugins. The functionality in this repository is being migrated. If this issue is still relevant please create a new issue in this repository:

https://github.com/awslabs/backstage-plugins-for-aws
