### ISSUE TITLE
Allow paging configurability to AWSCodePipelineWidget component to enable pagination of CodePipeline stages

### ISSUE THREAD

**Issue by Ma11hewThomas** [awslabs/aws-codeservices-plugins-for-backstage#60]
Hello,
Thank you to the team for creating a great plugin. 

When a CodePipeline has many stages, the height of the AWSCodePipelineWidget component is challenging to manage in the grid - demonstrated below. 

I've created this issue to add a paging configuration to AWSCodePipelineWidget component, allowing pagination of CodePipeline stages.

Thank you. 

<img width="492" alt="image" src="https://user-images.githubusercontent.com/25988124/220992157-2e07eb8f-dc94-46da-9431-78930bf3ff00.png">

**Comment by niallthomson** [comment]
We have started a new project to better scale our efforts regarding Backstage plugins. The functionality in this repository is being migrated. If this issue is still relevant please create a new issue in this repository:

https://github.com/awslabs/backstage-plugins-for-aws
