### ISSUE TITLE
How can I access the code-pipeline tab UI in backstage.

### ISSUE THREAD

**Issue by kales5078** [awslabs/aws-codeservices-plugins-for-backstage#79]
I installed the plugin as per given step. 
what URL I have to use to access code pipeline tab in backstage.

**Comment by niallthomson** [comment]
We have started a new project to better scale our efforts regarding Backstage plugins. The functionality in this repository is being migrated. If this issue is still relevant please create a new issue in this repository:

https://github.com/awslabs/backstage-plugins-for-aws
