### ISSUE TITLE
Can we view logs of CodeBuilds within Backstage.

### ISSUE THREAD

**Issue by anshulgargamway** [awslabs/aws-codeservices-plugins-for-backstage#8]
Is this possible to view logs of CodeBuilds within backstage ? As currently what I have observed it adds a link to codebuild but we were thinking if this possible to view directly the logs in backstage.

**Comment by nimakaviani** [comment]
This is an interesting idea @anshulgargamway ... we can definitely consider implementing it in a next release of the plugin. I will keep the issue open for us to track this.

**Comment by niallthomson** [comment]
We have started a new project to better scale our efforts regarding Backstage plugins. The functionality in this repository is being migrated. If this issue is still relevant please create a new issue in this repository:

https://github.com/awslabs/backstage-plugins-for-aws
